### ISSUE TITLE
`numpy` error when running CLI

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#61]
## Overview
I'm trying to just to run the CLI with either no commands, or with `generate-all`, and I'm getting this same error:

`AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?`

<details><summary>Stacktrace</summary>
<p>

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/joeflack4/projects/comploinc/src/comp_loinc/__init__.py", line 4, in <module>
    from comp_loinc.main import app
  File "/Users/joeflack4/projects/comploinc/src/comp_loinc/main.py", line 33, in <module>
    from comp_loinc.mapping.fhir_concept_map_ingest import ChebiFhirIngest
  File "/Users/joeflack4/projects/comploinc/src/comp_loinc/mapping/fhir_concept_map_ingest.py", line 6, in <module>
    from sssom.io import convert_file
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.10/site-packages/sssom/__init__.py", line 12, in <module>
    from sssom.util import (  # noqa:401
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.10/site-packages/sssom/util.py", line 510, in <module>
    def add_default_confidence(df: pd.DataFrame, confidence: float = np.NAN) -> pd.DataFrame:
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?
```

</p>
</details> 

## What I tried
I've installed my setup using `poetry install`.

**Comment by joeflack4** [comment]
As expected / hoped, this error has gone away in Shahim's new refactor.
