### ISSUE TITLE
Build fails: Slot lookup err

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#87]
## Overview
I'm now getting the following error during the `lt-primary-def` build.

```
ValueError: Lookup slot in LoincTerm failed for primary_scale_type // element=LoincTerm(id='100000-9'
```

<details><summary>Full log</summary>
<p>

```
import sys; print('Python %s on %s' % (sys.version, sys.platform))
/Users/joeflack4/virtualenvs/comp-loinc/bin/python -X pycache_prefix=/Users/joeflack4/Library/Caches/JetBrains/PyCharm2023.3/cpython-cache /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 62854 --file /Users/joeflack4/projects/comploinc/src/comp_loinc/cli.py --fast-run build 
Connected to pydev debugger (build 233.15325.20)
Running load_linkml_schema
2024-09-30 00:34:21 INFO     LoincBuilder    Starting save-owl
2024-09-30 00:34:22 INFO     LoincBuilder    save-owl document created.
Writing file: /Users/joeflack4/projects/comploinc/output/build-default/fast_run/loinc-part-list-all.owl
2024-09-30 00:34:22 INFO     LoincBuilder    save-owl writing document.
2024-09-30 00:34:22 INFO     LoincBuilder    save-owl writing document finished.
Running load_linkml_schema
2024-09-30 00:34:33 INFO     LoincBuilder    Starting save-owl
2024-09-30 00:39:47 INFO     LoincBuilder    save-owl document created.
Writing file: /Users/joeflack4/projects/comploinc/output/build-default/fast_run/loinc-part-hierarchy-all.owl
2024-09-30 00:39:47 INFO     LoincBuilder    save-owl writing document.
2024-09-30 00:40:09 INFO     LoincBuilder    save-owl writing document finished.
2024-09-30 00:40:09 INFO     LoincBuilder    Starting lt-inst-all
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 1000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 2000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 3000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 4000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 5000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 6000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 7000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 8000
2024-09-30 00:40:10 INFO     LoincBuilder    Finished 9000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 10000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished lt-inst-all
2024-09-30 00:40:11 INFO     LoincBuilder    Starting lt-class-roots
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 1000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 2000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 3000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 4000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 5000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 6000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 7000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 8000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished 9000
2024-09-30 00:40:11 INFO     LoincBuilder    Finished lt-class-roots
Running load_linkml_schema
2024-09-30 00:40:11 INFO     LoincBuilder    Starting save-owl
2024-09-30 00:45:44 INFO     LoincBuilder    save-owl document created.
Writing file: /Users/joeflack4/projects/comploinc/output/build-default/fast_run/loinc-terms-list-all.owl
2024-09-30 00:45:44 INFO     LoincBuilder    save-owl writing document.
2024-09-30 00:45:55 INFO     LoincBuilder    save-owl writing document finished.
2024-09-30 00:45:55 INFO     LoincBuilder    Starting lt-inst-all
2024-09-30 00:45:55 INFO     LoincBuilder    Finished 1000
2024-09-30 00:45:55 INFO     LoincBuilder    Finished 2000
2024-09-30 00:45:55 INFO     LoincBuilder    Finished 3000
2024-09-30 00:45:55 INFO     LoincBuilder    Finished 4000
2024-09-30 00:45:55 INFO     LoincBuilder    Finished 5000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished 6000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished 7000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished 8000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished 9000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished 10000
2024-09-30 00:45:56 INFO     LoincBuilder    Finished lt-inst-all
Running load_linkml_schema
2024-09-30 00:46:31 INFO     LoincBuilder    Starting save-owl
2024-09-30 00:46:31 ERROR    root            Did not find primary_scale_type in LoincTerm slots =  []
python-BaseException
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/projects/comploinc/src/comp_loinc/cli.py", line 171, in build
    self.cli(args)
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/projects/comploinc/src/comp_loinc/loinc_builder_steps.py", line 781, in save_to_owl
    document = owl_dumper.to_ontology_document(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/linkml_owl/dumpers/owl_dumper.py", line 165, in to_ontology_document
    self.transform(e1, schema)
  File "/Users/joeflack4/virtualenvs/comp-loinc/lib/python3.11/site-packages/linkml_owl/dumpers/owl_dumper.py", line 254, in transform
    raise ValueError(f'Lookup slot in {c.name} failed for {k} // element={element}')
ValueError: Lookup slot in LoincTerm failed for primary_scale_type // element=LoincTerm(id='100000-9', entity_label=None, entity_description=None, sub_class_of=[], equivalent_class=[], loinc_number=None, long_common_name=None, short_name=None, status=None, loinc_class=None, loinc_class_type=None, primary_component='LP431397-1', primary_property='LP6817-3', primary_time_aspect='LP6960-1', primary_system='LP310005-6', primary_scale_typ='LP7749-7', primary_method_typ=None, supplementary_property=None, supplementary_scale_typ=None, supplementary_method_typ=None, supplementary_analyte=None, supplementary_challenge=None, supplementary_adjustment=None, supplementary_count=None, supplementary_time_core=None, supplementary_time_modifier=None, supplementary_system_core=None, supplementary_super_system=None, supplementary_analyte_core=None, supplementary_analyte_suffix=None, supplementary_analyte_numerator=None, supplementary_analyte_divisor=None, supplementary_analyte_divisor_suffix=None, supplementary_analyte_gene=None, supplementary_analyte_genetic_variant=None, supplementary_analyte_chemical=None, supplementary_analyte_divisor_chemical=None, supplementary_analyte_clinical_drug=None, supplementary_system_core_anatomic_entity=None, supplementary_analyte_organism=None, supplementary_challenge_route=None, supplementary_analyte_allergen=None, supplementary_class=None, supplementary_category=None, supplementary_search=None, primary_rad_anatomic_location_imaging_focus=None, primary_rad_anatomic_location_laterality=None, primary_rad_anatomic_location_laterality_presence=None, primary_rad_anatomic_location_region_imaged=None, primary_rad_guidance_for_action=None, primary_rad_guidance_for_approach=None, primary_rad_guidance_for_object=None, primary_rad_guidance_for_presence=None, primary_rad_maneuver_maneuver_type=None, primary_rad_modality_subtype=None, primary_rad_modality_type=None, primary_rad_pharmaceutical_route=None, primary_rad_pharmaceutical_substance_given=None, primary_rad_reason_for_exam=None, primary_rad_subject=None, primary_rad_timing=None, primary_rad_view_aggregation=None, primary_rad_view_view_type=None, primary_document_kind=None, primary_document_role=None, primary_document_setting=None, primary_document_subject_matter_domain=None, primary_document_type_of_service=None)
 ```

</p>
</details> 

## Investigation
I tried several commits, and this error happens with the merge commit of:
- #73 

## Possible solutions
If I'm unable to find a quick solution, I'll likely temporarily reset `main` and re-apply some work.

Also thinking about a QC `--fast-run` build GH action, if it has enough memory.

**Comment by joeflack4** [comment]
Addressed by:
- 03f369aeb8e4dc422023bb30bd695be72f811953

**Comment by ShahimEssaid** [comment]
@joeflack4  see my commit comment.  This fix should be undone and let's try to figure out the root cause of the error.  I'm out this week but we can review next week if you like.,

**Comment by joeflack4** [comment]
@ShahimEssaid I saw it! Thanks for your attentiveness. See:
- https://github.com/loinc/comp-loinc/pull/73#discussion_r1782099948
